tosca_definitions_version: tosca_simple_yaml_1_3

metadata:
  template_name: "kubetos"
  template_author: "shishqa"
  template_version: "1.0"

imports:
  - profiles/openstack/main.yaml
  - profiles/cri/main.yaml

topology_template:
  node_templates:
    sg:
      type: openstack.nodes.SecurityGroup
      properties:
        name: shishqa-test-sg-opera
        description: sg created from xOpera

    sg_rule_tcp:
      type: openstack.nodes.SecurityGroupRule
      properties:
        protocol: tcp
        remote_ip_prefix: 0.0.0.0/0
      requirements:
        - security_group: sg

    sg_rule_udp:
      type: openstack.nodes.SecurityGroupRule
      properties:
        protocol: udp
        remote_ip_prefix: 0.0.0.0/0
      requirements:
        - security_group: sg

    sg_rule_icmp:
      type: openstack.nodes.SecurityGroupRule
      properties:
        protocol: icmp
        remote_ip_prefix: 0.0.0.0/0
      requirements:
        - security_group: sg

    compute:
      type: openstack.nodes.Compute
      properties:
        name: shishqa-test-xopera
        image: "Ubuntu Server 20.04 LTS (Focal Fossa)"
        flavor: Standard1.small.s50
        network: net-for-intra-sandbox
        floating_ip_pool: ispras
        key_name: shishqa
      requirements:
        - security_group: sg
      artifacts:
        ssh_key: id_rsa

    runc:
      type: kubetos.nodes.Runc
      capabilities:
        oci:
          properties:
            name: runc
            path: /usr/sbin/runc
      requirements:
        - host: compute
      artifacts:
        ssh_key: id_rsa
