- name: Create directories
  file:
    path: "{{ path | dirname }}"
    mode: 0644
    state: directory

- name: Write kubeconfig
  copy:
    dest: "{{ path }}"
    content: "{{ kubeconfig }}"
    mode: 0644
