---
- hosts: all
  gather_facts: yes
  vars:
    ansible_ssh_user: ubuntu
    ansible_become: yes
  tasks:

    - name: Update list of peers
      set_stats:
        data:
          peer_addresses: "{{ peer_addresses + [ peer_address ] }}"
          access_addresses: "{{ access_addresses + [ access_address ] }}"
