---
- hosts: localhost
  gather_facts: no
  tasks:

    - name: Create security group rule
      os_security_group_rule:
        state: present
        security_group: "{{ security_group }}"
        direction: "{{ rule_direction }}"
        ethertype: "{{ rule_ethertype }}"
        port_range_max: "{{ rule_port_range_max }}"
        port_range_min: "{{ rule_port_range_min }}"
        protocol: "{{ rule_protocol }}"
        remote_ip_prefix: "{{ rule_remote_ip_prefix }}"
      register: sg_rule_info

    - name: Set attributes
      set_stats:
        data:
          id: "{{ sg_rule_info.id }}"
