---
- name: kata-containers | Download kata binary
  import_role:
    name: download
    tasks_from: download_file
  vars:
    download:
      file: true
      version: "{{ kata_containers_version }}"
      dest: "/tmp/releases/kata-static-{{ kata_containers_version }}-{{ image_arch }}.tar.xz"
      sha256: "{{ kata_containers_binary_checksum }}"
      url: "{{ kata_containers_download_url }}"
      unarchive: false
      owner: "root"
      mode: "0755"

- name: kata-containers | Copy kata-containers binary
  unarchive:
    src: "/tmp/releases/kata-static-{{ kata_containers_version }}-{{ image_arch }}.tar.xz"
    dest: "/"
    mode: 0755
    remote_src: yes
