---
- name: kata-containers | Create config directory
  file:
    path: "{{ kata_containers_config_dir }}"
    state: directory
    mode: 0755

- name: kata-containers | Set configuration
  template:
    src: "{{ item }}.j2"
    dest: "{{ kata_containers_config_dir }}/{{ item }}"
    mode: 0644
  with_items:
    - configuration-qemu.toml
