---
- name: install | Download etcd and etcdctl
  import_role:
    name: download
    tasks_from: download_file
  vars:
    download:
      container: false
      file: true
      version: "{{ etcd_version }}"
      dest: "{{ local_release_dir }}/etcd-{{ etcd_version }}-linux-{{ host_architecture }}.tar.gz"
      sha256: "{{ etcd_binary_checksum }}"
      url: "{{ etcd_download_url }}"
      unarchive: true
      owner: "root"
      mode: "0755"
  tags:
    - etcd

- name: install | Copy etcd and etcdctl binary from download dir
  copy:
    src: "{{ local_release_dir }}/etcd-{{ etcd_version }}-linux-{{ host_architecture }}/{{ item }}"
    dest: "{{ bin_dir }}/{{ item }}"
    mode: 0755
    remote_src: yes
  with_items:
    - etcd
    - etcdctl
