---
- block:
  - name: download_file | Create dest directory on node
    file:
      path: "{{ local_release_dir + download.dest | dirname }}"
      owner: "{{ download.owner | default(omit) }}"
      mode: 0755
      state: directory
      recurse: yes
    become: yes

  # This must always be called, to check if the checksum matches. On no-match the file is re-downloaded.
  # This task will avoid logging it's parameters to not leak environment passwords in the log
  - name: download_file | Download item
    get_url:
      url: "{{ download.url }}"
      dest: "{{ download.dest }}"
      owner: "{{ download.owner | default(omit) }}"
      mode: "{{ download.mode | default(omit) }}"
      checksum: "{{ 'sha256:' + download.sha256 if download.sha256 else omit }}"
      validate_certs: "{{ download_validate_certs }}"
      url_username: "{{ download.username | default(omit) }}"
      url_password: "{{ download.password | default(omit) }}"
      force_basic_auth: "{{ download.force_basic_auth | default(omit) }}"
    run_once: "{{ download_force_cache }}"
    register: get_url_result
    become: yes
    until: "'OK' in get_url_result.msg or 'file already exists' in get_url_result.msg"
    retries: 4
    delay: "{{ retry_stagger | default(5) }}"
    no_log: false

  - name: "download_file | Extract file archives"
    include_tasks: "extract_file.yml"

  tags:
  - download
