- hosts: localhost
  connection: local
  gather_facts: no
  vars:
    ansible_become: yes
  tasks:

    - name: Make sure directories exists
      file:
        name: "/tmp/cfssl/{{ tosca_id }}"
        state: directory
        mode: 0644

    - name: Create cert csr
      template:
        src: csr.json.j2
        dest: "/tmp/cfssl/{{ tosca_id }}/csr.json"
        mode: 0644

    - name: sign cert
      shell:
        cmd: cfssl gencert -initca csr.json | cfssljson -bare ca
        chdir: "/tmp/cfssl/{{ tosca_id }}"

    - name: get cert
      shell: "cat /tmp/cfssl/{{ tosca_id }}/ca.pem"
      register: cert

    - name: get key
      shell: "cat /tmp/cfssl/{{ tosca_id }}/ca-key.pem"
      register: key

    - name: return cert
      set_stats:
        data:
          cert: "{{ cert.stdout }}"
          key: "{{ key.stdout }}"
