- hosts: localhost
  connection: local
  gather_facts: no
  tasks:

    - name: Write ca cert
      copy:
        dest: ca.pem
        content: "{{ ca_cert }}"
        mode: 0644

    - name: Write ca key
      copy:
        dest: ca-key.pem
        content: "{{ ca_key }}"
        mode: 0644

    - name: Create cert csr
      template:
        src: csr.json.j2
        dest: csr.json
        mode: 0644

    - name: sign cert
      shell:
        cmd: >-
          cfssl gencert \
            -ca=ca.pem \
            -ca-key=ca-key.pem \
            -config=ca-config.json \
            {%- if hostnames != [] -%}-hostname={{ hostnames | join(',') }} \{%- endif -%}
            -profile=default \
            csr.json | cfssljson -bare cert

    - name: get cert
      shell: cat cert.pem
      register: cert

    - name: get key
      shell: cat cert-key.pem
      register: key

    - name: return cert
      set_stats:
        data:
          cert: "{{ cert.stdout }}"
          key: "{{ key.stdout }}"
