---
- hosts: all
  gather_facts: yes
  vars:
    ansible_become: yes
  tasks:

    - name: Create kubeconfig
      shell: >-
        kubectl config set-cluster default-cluster \
        --certificate-authority={{ ca_cert_path }} \
        --embed-certs=true \
        --server=https://{{ apiserver_address }}:{{ apiserver_port }} \
        --kubeconfig={{ kubeconfig_path }}

    - name: Create user
      shell: >-
        kubectl config set-credentials {{ user }} \
        --client-certificate={{ cert_path }} \
        --client-key={{ key_path }} \
        --embed-certs=true \
        --kubeconfig={{ kubeconfig_path }}

    - name: Create context
      shell: >-
        kubectl config set-context default \
        --cluster=default-cluster \
        --user={{ user }} \
        --kubeconfig={{ kubeconfig_path }}

    - name: Use context
      shell: >-
        kubectl config use-context default \
        --kubeconfig={{ kubeconfig_path }}
