---
- hosts: all
  gather_facts: yes
  vars:
    ansible_ssh_user: ubuntu
    ansible_ssh_private_key_file: "{{ ssh_key }}"
    ansible_become: yes
  tasks:

    - name: Create Kubelet
      include_role:
        name: kubernetes/kubelet
        tasks_from: configure
