---

- name: Create security group
  os_security_group:
    state: present
    name: "{{ config.name }}"
    description: "{{ config.description }}"

- os_security_group_rule:
    security_group: "{{ config.name }}"
    protocol: icmp
    remote_ip_prefix: 0.0.0.0/0

- os_security_group_rule:
    security_group: "{{ config.name }}"
    protocol: tcp
    remote_ip_prefix: 0.0.0.0/0

- os_security_group_rule:
    security_group: "{{ config.name }}"
    protocol: udp
    remote_ip_prefix: 0.0.0.0/0

- name: Export config
  set_fact:
    config: "{{ config }}"
  delegate_to: "{{ uid }}"
  delegate_facts: true
