---
- hosts: localhost
  gather_facts: no
  tasks:

    - name: Write ca cert
      copy:
        dest: ca.pem
        content: "{{ ca_cert }}"
        mode: 0644

    - name: Write cert
      copy:
        dest: cert.pem
        content: "{{ cert }}"
        mode: 0644

    - name: Write key
      copy:
        dest: key.pem
        content: "{{ key }}"
        mode: 0644

    - name: Create kubeconfig
      shell: >-
        kubectl config set-cluster {{ cluster_name }} \
        --certificate-authority=ca.pem \
        --embed-certs=true \
        --server=https://{{ apiserver_address }}:{{ apiserver_port }} \
        --kubeconfig=kube.conf

    - name: Create user
      shell: >-
        kubectl config set-credentials {{ user_name }} \
        --client-certificate=cert.pem \
        --client-key=key.pem \
        --embed-certs=true \
        --kubeconfig=kube.conf

    - name: Create context
      shell: >-
        kubectl config set-context default \
        --cluster={{ cluster_name }} \
        --user={{ user_name }} \
        --kubeconfig=kube.conf

    - name: Use context
      shell: >-
        kubectl config use-context default \
        --kubeconfig=kube.conf

    - name: get kubeconfig
      shell: cat kube.conf
      register: kubeconfig

    - name: return cert
      set_fact:
        kubeconfig: "{{ kubeconfig.stdout }}"
