---
- hosts: all
  gather_facts: yes
  vars:
    ansible_become: yes
  tasks:

    - name: Install packages
      package:
        name: "{{ item }}"
        state: present
      with_items:
        - socat
        - conntrack
        - ipset
      register: package_install
      until: package_install is succeeded
      retries: 4

    - name: Remove swapfile from /etc/fstab
      mount:
        name: "{{ item }}"
        fstype: swap
        state: absent
      with_items:
        - swap
        - none

    - name: check swap
      command: /sbin/swapon -s
      register: swapon
      changed_when: no

    - name: Disable swap
      command: /sbin/swapoff -a
      when: swapon.stdout

    - name: Verify if br_netfilter module exists
      command: "modinfo br_netfilter"
      environment:
        PATH: "{{ ansible_env.PATH }}:/sbin"  # Make sure we can workaround RH's conservative path management
      register: modinfo_br_netfilter
      failed_when: modinfo_br_netfilter.rc not in [0, 1]
      changed_when: false

    - name: Verify br_netfilter module path exists
      file:
        path: /etc/modules-load.d
        state: directory
        mode: 0755

    - name: Enable br_netfilter module
      modprobe:
        name: br_netfilter
        state: present
      when: modinfo_br_netfilter.rc == 0

    - name: Persist br_netfilter module
      copy:
        dest: /etc/modules-load.d/kubespray-br_netfilter.conf
        content: br_netfilter
        mode: 0644
      when: modinfo_br_netfilter.rc == 0

    # kube-proxy needs net.bridge.bridge-nf-call-iptables enabled when found if br_netfilter is not a module
    - name: Check if bridge-nf-call-iptables key exists
      command: "sysctl net.bridge.bridge-nf-call-iptables"
      failed_when: false
      changed_when: false
      register: sysctl_bridge_nf_call_iptables

    - name: Enable bridge-nf-call tables
      sysctl:
        name: "{{ item }}"
        state: present
        sysctl_file: "/etc/sysctl.d/99-sysctl.conf"
        value: "1"
        reload: yes
      when: sysctl_bridge_nf_call_iptables.rc == 0
      with_items:
        - net.bridge.bridge-nf-call-iptables
        - net.bridge.bridge-nf-call-arptables
        - net.bridge.bridge-nf-call-ip6tables

    - name: Modprobe Kernel Module for IPVS
      modprobe:
        name: "{{ item }}"
        state: present
      with_items:
        - ip_vs
        - ip_vs_rr
        - ip_vs_wrr
        - ip_vs_sh
      tags:
        - kube-proxy

    - name: Modprobe nf_conntrack_ipv4
      modprobe:
        name: nf_conntrack_ipv4
        state: present
      register: modprobe_nf_conntrack_ipv4
      ignore_errors: true  # noqa ignore-errors
      tags:
        - kube-proxy

    - name: Persist ip_vs modules
      copy:
        dest: /etc/modules-load.d/kube_proxy-ipvs.conf
        mode: 0644
        content: |
          ip_vs
          ip_vs_rr
          ip_vs_wrr
          ip_vs_sh
          {% if modprobe_nf_conntrack_ipv4 is success -%}
          nf_conntrack_ipv4
          {%-   endif -%}
      tags:
        - kube-proxy
