---
- hosts: localhost
  connection: local
  gather_facts: no
  vars:
    server_name: shishqa-test-from-ansible
    server_image: 7ce7a4b7-e085-47ba-a73b-61cf138b5f92
    server_flavor: bbd08a93-6c32-43e0-8b2a-f91a89425134
    server_keypair: shishqa-toadster
    server_network: net-for-intra-sandbox
  tasks:

    - name: Create instance
      openstack.cloud.server:
        state: present
        name: "{{ server_name }}"
        image: "{{ server_image }}" # matched with os_flavor_find.yaml
        flavor: "{{ server_flavor }}" # matched with os_image_find.yaml
        key_name: "{{ server_keypair }}"
        nics: 
          - net-name: "{{ server_network }}"
          # - net-name: ispras
        boot_from_volume: false
        security_groups: ["default"]
        auto_ip: false
      register: server_info

    - name: get server info
      openstack.cloud.server_info:
        server: "shishqa-test-from-ansible"
      register: result

    - debug:
        msg: "{{ result.openstack_servers }}"

    - name: print networks attrubute
      debug:
        msg: "{{ result.openstack_servers[0].addresses }}"