---
- hosts: all
  gather_facts: yes
  tasks:

    - name: Create instance
      os_server:
        state: present
        name: "{{ vm_name }}"
        image: "{{ image }}"
        flavor: "{{ flavor }}"
        key_name: "{{ key_name }}"
        network: "{{ network }}"
        boot_from_volume: false
        security_groups: "{{ security_groups }}"
        auto_ip: false
      register: server_info

    - name: Acquire floating IPs for instance
      os_floating_ip:
        state: present
        reuse: yes
        server: "{{ server_info.server.id }}"
        network: "{{ floating_ip_pool }}"
        wait: yes
      when: server_info.server.public_v4 == ''

    - name: Retrieve openstack facts
      os_server_info:
        filters:
          id: "{{ server_info.server.id }}"
      register: server_facts

    - name: Set attributes
      set_stats:
        data:
          private_address: "{{ server_facts.openstack_servers[0].private_v4 }}"
          public_address: "{{ server_facts.openstack_servers[0].public_v4 }}"
          id: "{{ server_facts.openstack_servers[0].id }}"

    - name: Create temporary inventory for ssh wait
      add_host:
        name: server
        groups: vms
        ansible_host: "{{ server_facts.openstack_servers[0].public_v4 }}"
        ansible_user: ubuntu
        ansible_ssh_private_key_file: "{{ ssh_key }}"
        ansible_ssh_common_args: >
          -o IdentitiesOnly=yes
          -o BatchMode=yes
          -o UserKnownHostsFile=/dev/null
          -o StrictHostKeyChecking=no

- hosts: vms
  gather_facts: no
  tasks:
    - name: Wait for ssh to wake up
      wait_for_connection:
        delay: 10
        sleep: 5
        timeout: 120
